site_name: ahd; Ad-Hoc Dispatcher

nav:
    - Home: index.md

theme: readthedocs

repo_url: https://github.com/Descent098/ahd

site_description: Create ad-hoc commands to be dispatched in their own namespace.

site_author: Kieran Wood | Descent098
