site_name: Ad-Hoc Dispatcher

nav:
    - Overview: index.md
    - Quick Start: quick-start.md
    - Usage: usage.md
    - Advanced Usage/Details: advanced-usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Glossary: glossary.md

theme: readthedocs

repo_url: https://github.com/Descent098/ahd

site_description: Create ad-hoc commands to be dispatched in their own namespace.

site_author: Kieran Wood | Descent098
