name: Testing

on: 
  push:
    branches:
    - '**'
  schedule:
    # Run at 12:00 AM, on day 10 of the month, every 2 months
    - cron:  '0 0 10 */2 *'

jobs:
  test:
    name: Test on Python ${{ matrix.python_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: ['3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        pip install .
        pip install pytest
    - name: Test with pytest
      run: |
        pytest
